groups:
  format:
    country_category: "{flag} {country} | {category}"
    world_category: "🌍 WORLD | {category}"

  defaults:
    country: "WORLD"
    category: "general"

  examples:
    - "🇨🇿 CZ | General"
    - "🇨🇿 CZ | Documentary"
    - "🇸🇰 SK | Sport"
    - "🇺🇦 UA | News"
    - "🌍 WORLD | Music"